/*
 jQuery UI - v1.12.1 - 2016-10-03 * http://jqueryui.com * Includes: widget.js, keycode.js, widgets/mouse.js, widgets/slider.js * Copyright jQuery Foundation and other contributors; Licensed MIT */
String.prototype.trim||(String.prototype.trim=function(){return this.replace(/^[\s\uFEFF\xA0]+|[\s\uFEFF\xA0]+$/g,"")});
"function"!==typeof String.prototype.replaceSpecialChars&&(String.prototype.replaceSpecialChars=function(){var c={"\u00e7":"c","\u00e6":"ae","\u0153":"oe","\u00e1":"a","\u00e9":"e","\u00ed":"i","\u00f3":"o","\u00fa":"u","\u00e0":"a","\u00e8":"e","\u00ec":"i","\u00f2":"o","\u00f9":"u","\u00e4":"a","\u00eb":"e","\u00ef":"i","\u00f6":"o","\u00fc":"u","\u00ff":"y","\u00e2":"a","\u00ea":"e","\u00ee":"i","\u00f4":"o","\u00fb":"u","\u00e5":"a","\u00e3":"a","\u00f8":"o","\u00f5":"o",u:"u","\u00c1":"A","\u00c9":"E",
"\u00cd":"I","\u00d3":"O","\u00da":"U","\u00ca":"E","\u00d4":"O","\u00dc":"U","\u00c3":"A","\u00d5":"O","\u00c0":"A","\u00c7":"C"};return this.replace(/[\u00e0-\u00fa]/ig,function(l){return"undefined"!=typeof c[l]?c[l]:l})});
Array.prototype.indexOf||(Array.prototype.indexOf=function(c,l){var h;if(null==this)throw new TypeError('"this" is null or not defined');var n=Object(this),a=n.length>>>0;if(0===a)return-1;h=+l||0;Infinity===Math.abs(h)&&(h=0);if(h>=a)return-1;for(h=Math.max(0<=h?h:a-Math.abs(h),0);h<a;){if(h in n&&n[h]===c)return h;h++}return-1});
var Common={run:function(){},init:function(){},ajaxStop:function(){},windowOnload:function(){}},Home={init:function(){},ajaxStop:function(){},windowOnload:function(){}},Search={init:function(){},ajaxStop:function(){},windowOnload:function(){}},Product={run:function(){},init:function(){Product.product360()},ajaxStop:function(){},windowOnload:function(){},product360:function(){function c(){var c=$(".y-productImg").addClass("qd-v1-product-360"),l=c.find(".thumbs");c.find(".qd-v1-product-360-image").length||
l.find(".qd-v1-product-360-thumb").length||($(".thumbs a").click(function(){c.removeClass("qd-v1-product-360-show")}),l.find("li:first").clone().appendTo(l).addClass("qd-v1-product-360-thumb").click(function(){c.addClass("qd-v1-product-360-show");if(!c.find(".qd-v1-product-360-image").length){c.find("#image").after('<div class="qd-v1-product-360-image"> <div class="threesixty"> <div class="spinner"> <span>0%</span> </div> <ol class="threesixty_images"></ol> </div> <div class="qd-v1-product-360-slider"> <i class="qd-v1-product-360-icon qd-v1-product-360-play"></i> <i class="qd-v1-product-360-icon qd-v1-product-360-stop"></i> <div class="slider"></div> <i class="qd-v1-product-360-icon qd-v1-product-360-question"></i> <div class="qd-v1-product-360-text" style="display: none;"> <p>Clique no bot\u00e3o \u201cARRASTE\u201d  e arraste para visualizar mais detalhes do produto.</p> </div> </div> </div>');
var a=$(".qd-v1-product-360-slider .slider"),b=!0,e=$(".qd-v1-product-360-image .threesixty"),d=e.offset().left,f=e.width();$(window).resize(function(a){d=e.offset().left;f=e.width()});product360=$(".qd-v1-product-360-image .threesixty").ThreeSixty({totalFrames:16,endFrame:16,currentFrame:1,imgList:".threesixty_images",progress:".spinner",imagePath:"http://montecarlo.vtexcommercestable.com.br/arquivos/"+skuJson.productId+"_",filePrefix:"",ext:".jpg",drag:!1,responsive:!0,width:500,height:500,playSpeed:162,
autoplayDirection:-1,onReady:function(){e.mousemove(function(c){b&&(x=Math.round(16*(c.pageX-d)/f),a.slider("value",x),product360.gotoAndPlay(x))});a.slider({max:16,slide:function(a,b){product360.gotoAndPlay(b.value)}})}});var g={},k=c.find(".qd-v1-product-360-play"),m=c.find(".qd-v1-product-360-stop");moveSlider=function(){b||(g[15]?($(".qd-v1-product-360-stop").click(),g={}):(g[product360.getNormalizedCurrentFrame()]=!0,setTimeout(function(){a.slider("value",product360.getNormalizedCurrentFrame());
moveSlider()},49)))};k.click(function(){a.slider("value",0);product360.gotoAndPlay(0);product360.play();b=!1;moveSlider();$(this).hide();m.show()});m.click(function(){product360.stop();b=!0;$(this).hide();k.show()});$(".qd-v1-product-360-question").hover(function(){$(".qd-v1-product-360-text").show()},function(){$(".qd-v1-product-360-text").hide()})}}))}var l=window.ImageControl;window.ImageControl=function(){$.ajax({url:"//montecarlo.vteximg.com.br/arquivos/"+skuJson.productId+"_16.jpg"}).done(c);
l.apply(this,arguments)};$(window).on("skuSelected.vtex",function(){$(".y-productImg").is(".qd-v1-product-360")&&($(".y-productImg").removeClass("qd-v1-product-360-show"),$(".qd-v1-product-360-image").remove(),c())})}},List={run:function(){},init:function(){},ajaxStop:function(){},windowOnload:function(){}},Institutional={init:function(){},ajaxStop:function(){},windowOnload:function(){}},Orders={init:function(){},ajaxStop:function(){},windowOnload:function(){}};
try{(function(){var c,l,h;Search.isSearch=$(document.body).is(".resultado-busca");Search.isDepartament=$(document.body).is(".departamento");Search.isCategory=$(document.body).is(".categoria");h=function(){Common.windowOnload();c.is(".home")?Home.windowOnload():c.is(".resultado-busca, .departamento, .categoria")?Search.windowOnload():c.is(".produto")?Product.windowOnload():c.is(".listas")?List.windowOnload():c.is(".institucional")?Institutional.windowOnload():c.is(".orders")&&Orders.windowOnload()};
l=function(){Common.ajaxStop();c.is(".home")?Home.ajaxStop():c.is(".resultado-busca, .departamento, .categoria")?Search.ajaxStop():c.is(".produto")?Product.ajaxStop():c.is(".listas")?List.ajaxStop():c.is(".institucional")?Institutional.ajaxStop():c.is(".orders")&&Orders.ajaxStop()};$(function(){c=$(document.body);Common.init();c.is(".home")?Home.init():c.is(".resultado-busca, .departamento, .categoria")?Search.init():c.is(".produto")?Product.init():c.is(".listas")?List.init():c.is(".institucional")?
Institutional.init():c.is(".orders")&&Orders.init();$(document).ajaxStop(l);$(window).load(h);c.addClass("jsFullLoaded")});Common.run();"/p"==location.pathname.substr(location.pathname.length-2,2).toLowerCase()?Product.run():0==location.pathname.search(/^(\/giftlist|\/list\/)/)&&List.run()})()}catch(c){"undefined"!==typeof console&&"function"===typeof console.error&&$("body").addClass("jsFullLoaded jsFullLoadedError")&&console.error("Houve um erro ao iniciar os objetos. Detalhes: "+c.message)}
(function(c){"function"==typeof define&&define.amd?define(["jquery"],c):c(jQuery)})(function(c){c.ui=c.ui||{};c.ui.version="1.12.1";var l=0,h=Array.prototype.slice;c.cleanData=function(a){return function(b){var e,d,f;for(f=0;null!=(d=b[f]);f++)try{(e=c._data(d,"events"))&&e.remove&&c(d).triggerHandler("remove")}catch(g){}a(b)}}(c.cleanData);c.widget=function(a,b,e){var d,f,g,k={},m=a.split(".")[0];a=a.split(".")[1];var p=m+"-"+a;return e||(e=b,b=c.Widget),c.isArray(e)&&(e=c.extend.apply(null,[{}].concat(e))),
c.expr[":"][p.toLowerCase()]=function(a){return!!c.data(a,p)},c[m]=c[m]||{},d=c[m][a],f=c[m][a]=function(a,b){return this._createWidget?(arguments.length&&this._createWidget(a,b),void 0):new f(a,b)},c.extend(f,d,{version:e.version,_proto:c.extend({},e),_childConstructors:[]}),g=new b,g.options=c.widget.extend({},g.options),c.each(e,function(a,e){return c.isFunction(e)?(k[a]=function(){function c(){return b.prototype[a].apply(this,arguments)}function d(c){return b.prototype[a].apply(this,c)}return function(){var a,
b=this._super,f=this._superApply;return this._super=c,this._superApply=d,a=e.apply(this,arguments),this._super=b,this._superApply=f,a}}(),void 0):(k[a]=e,void 0)}),f.prototype=c.widget.extend(g,{widgetEventPrefix:d?g.widgetEventPrefix||a:a},k,{constructor:f,namespace:m,widgetName:a,widgetFullName:p}),d?(c.each(d._childConstructors,function(a,b){var e=b.prototype;c.widget(e.namespace+"."+e.widgetName,f,b._proto)}),delete d._childConstructors):b._childConstructors.push(f),c.widget.bridge(a,f),f};c.widget.extend=
function(a){for(var b,e,d=h.call(arguments,1),f=0,g=d.length;g>f;f++)for(b in d[f])e=d[f][b],d[f].hasOwnProperty(b)&&void 0!==e&&(a[b]=c.isPlainObject(e)?c.isPlainObject(a[b])?c.widget.extend({},a[b],e):c.widget.extend({},e):e);return a};c.widget.bridge=function(a,b){var e=b.prototype.widgetFullName||a;c.fn[a]=function(d){var f="string"==typeof d,g=h.call(arguments,1),k=this;return f?this.length||"instance"!==d?this.each(function(){var b,f=c.data(this,e);return"instance"===d?(k=f,!1):f?c.isFunction(f[d])&&
"_"!==d.charAt(0)?(b=f[d].apply(f,g),b!==f&&void 0!==b?(k=b&&b.jquery?k.pushStack(b.get()):b,!1):void 0):c.error("no such method '"+d+"' for "+a+" widget instance"):c.error("cannot call methods on "+a+" prior to initialization; attempted to call method '"+d+"'")}):k=void 0:(g.length&&(d=c.widget.extend.apply(null,[d].concat(g))),this.each(function(){var a=c.data(this,e);a?(a.option(d||{}),a._init&&a._init()):c.data(this,e,new b(d,this))})),k}};c.Widget=function(){};c.Widget._childConstructors=[];
c.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"<div>",options:{classes:{},disabled:!1,create:null},_createWidget:function(a,b){b=c(b||this.defaultElement||this)[0];this.element=c(b);this.uuid=l++;this.eventNamespace="."+this.widgetName+this.uuid;this.bindings=c();this.hoverable=c();this.focusable=c();this.classesElementLookup={};b!==this&&(c.data(b,this.widgetFullName,this),this._on(!0,this.element,{remove:function(a){a.target===b&&this.destroy()}}),this.document=c(b.style?
b.ownerDocument:b.document||b),this.window=c(this.document[0].defaultView||this.document[0].parentWindow));this.options=c.widget.extend({},this.options,this._getCreateOptions(),a);this._create();this.options.disabled&&this._setOptionDisabled(this.options.disabled);this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:function(){return{}},_getCreateEventData:c.noop,_create:c.noop,_init:c.noop,destroy:function(){var a=this;this._destroy();c.each(this.classesElementLookup,
function(b,c){a._removeClass(c,b)});this.element.off(this.eventNamespace).removeData(this.widgetFullName);this.widget().off(this.eventNamespace).removeAttr("aria-disabled");this.bindings.off(this.eventNamespace)},_destroy:c.noop,widget:function(){return this.element},option:function(a,b){var e,d,f,g=a;if(0===arguments.length)return c.widget.extend({},this.options);if("string"==typeof a)if(g={},e=a.split("."),a=e.shift(),e.length){d=g[a]=c.widget.extend({},this.options[a]);for(f=0;e.length-1>f;f++)d[e[f]]=
d[e[f]]||{},d=d[e[f]];if(a=e.pop(),1===arguments.length)return void 0===d[a]?null:d[a];d[a]=b}else{if(1===arguments.length)return void 0===this.options[a]?null:this.options[a];g[a]=b}return this._setOptions(g),this},_setOptions:function(a){for(var b in a)this._setOption(b,a[b]);return this},_setOption:function(a,b){return"classes"===a&&this._setOptionClasses(b),this.options[a]=b,"disabled"===a&&this._setOptionDisabled(b),this},_setOptionClasses:function(a){var b,e,d;for(b in a)d=this.classesElementLookup[b],
a[b]!==this.options.classes[b]&&d&&d.length&&(e=c(d.get()),this._removeClass(d,b),e.addClass(this._classes({element:e,keys:b,classes:a,add:!0})))},_setOptionDisabled:function(a){this._toggleClass(this.widget(),this.widgetFullName+"-disabled",null,!!a);a&&(this._removeClass(this.hoverable,null,"ui-state-hover"),this._removeClass(this.focusable,null,"ui-state-focus"))},enable:function(){return this._setOptions({disabled:!1})},disable:function(){return this._setOptions({disabled:!0})},_classes:function(a){function b(b,
g){var f,m;for(m=0;b.length>m;m++)f=d.classesElementLookup[b[m]]||c(),f=a.add?c(c.unique(f.get().concat(a.element.get()))):c(f.not(a.element).get()),d.classesElementLookup[b[m]]=f,e.push(b[m]),g&&a.classes[b[m]]&&e.push(a.classes[b[m]])}var e=[],d=this;return a=c.extend({element:this.element,classes:this.options.classes||{}},a),this._on(a.element,{remove:"_untrackClassesElement"}),a.keys&&b(a.keys.match(/\S+/g)||[],!0),a.extra&&b(a.extra.match(/\S+/g)||[]),e.join(" ")},_untrackClassesElement:function(a){var b=
this;c.each(b.classesElementLookup,function(e,d){-1!==c.inArray(a.target,d)&&(b.classesElementLookup[e]=c(d.not(a.target).get()))})},_removeClass:function(a,b,c){return this._toggleClass(a,b,c,!1)},_addClass:function(a,b,c){return this._toggleClass(a,b,c,!0)},_toggleClass:function(a,b,c,d){d="boolean"==typeof d?d:c;var e="string"==typeof a||null===a;a={extra:e?b:c,keys:e?a:b,element:e?this.element:a,add:d};return a.element.toggleClass(this._classes(a),d),this},_on:function(a,b,e){var d,f=this;"boolean"!=
typeof a&&(e=b,b=a,a=!1);e?(b=d=c(b),this.bindings=this.bindings.add(b)):(e=b,b=this.element,d=this.widget());c.each(e,function(e,k){function g(){return a||!0!==f.options.disabled&&!c(this).hasClass("ui-state-disabled")?("string"==typeof k?f[k]:k).apply(f,arguments):void 0}"string"!=typeof k&&(g.guid=k.guid=k.guid||g.guid||c.guid++);var h=e.match(/^([\w:-]*)\s*(.*)$/),l=h[1]+f.eventNamespace;(h=h[2])?d.on(l,h,g):b.on(l,g)})},_off:function(a,b){b=(b||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;
a.off(b).off(b);this.bindings=c(this.bindings.not(a).get());this.focusable=c(this.focusable.not(a).get());this.hoverable=c(this.hoverable.not(a).get())},_delay:function(a,b){var c=this;return setTimeout(function(){return("string"==typeof a?c[a]:a).apply(c,arguments)},b||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){this._addClass(c(a.currentTarget),null,"ui-state-hover")},mouseleave:function(a){this._removeClass(c(a.currentTarget),null,"ui-state-hover")}})},
_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(a){this._addClass(c(a.currentTarget),null,"ui-state-focus")},focusout:function(a){this._removeClass(c(a.currentTarget),null,"ui-state-focus")}})},_trigger:function(a,b,e){var d,f=this.options[a];if(e=e||{},b=c.Event(b),b.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase(),b.target=this.element[0],a=b.originalEvent)for(d in a)d in b||(b[d]=a[d]);return this.element.trigger(b,e),!(c.isFunction(f)&&
!1===f.apply(this.element[0],[b].concat(e))||b.isDefaultPrevented())}};c.each({show:"fadeIn",hide:"fadeOut"},function(a,b){c.Widget.prototype["_"+a]=function(e,d,f){"string"==typeof d&&(d={effect:d});var g,k=d?!0===d||"number"==typeof d?b:d.effect||b:a;d=d||{};"number"==typeof d&&(d={duration:d});g=!c.isEmptyObject(d);d.complete=f;d.delay&&e.delay(d.delay);g&&c.effects&&c.effects.effect[k]?e[a](d):k!==a&&e[k]?e[k](d.duration,d.easing,f):e.queue(function(b){c(this)[a]();f&&f.call(e[0]);b()})}});c.widget;
c.ui.keyCode={BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38};c.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());var n=!1;c(document).on("mouseup",function(){n=!1});c.widget("ui.mouse",{version:"1.12.1",options:{cancel:"input, textarea, button, select, option",distance:1,delay:0},_mouseInit:function(){var a=this;this.element.on("mousedown."+this.widgetName,function(b){return a._mouseDown(b)}).on("click."+
this.widgetName,function(b){return!0===c.data(b.target,a.widgetName+".preventClickEvent")?(c.removeData(b.target,a.widgetName+".preventClickEvent"),b.stopImmediatePropagation(),!1):void 0});this.started=!1},_mouseDestroy:function(){this.element.off("."+this.widgetName);this._mouseMoveDelegate&&this.document.off("mousemove."+this.widgetName,this._mouseMoveDelegate).off("mouseup."+this.widgetName,this._mouseUpDelegate)},_mouseDown:function(a){if(!n){this._mouseMoved=!1;this._mouseStarted&&this._mouseUp(a);
this._mouseDownEvent=a;var b=this,e=1===a.which,d="string"==typeof this.options.cancel&&a.target.nodeName?c(a.target).closest(this.options.cancel).length:!1;return e&&!d&&this._mouseCapture(a)?(this.mouseDelayMet=!this.options.delay,this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){b.mouseDelayMet=!0},this.options.delay)),this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&(this._mouseStarted=!1!==this._mouseStart(a),!this._mouseStarted)?(a.preventDefault(),!0):(!0===c.data(a.target,
this.widgetName+".preventClickEvent")&&c.removeData(a.target,this.widgetName+".preventClickEvent"),this._mouseMoveDelegate=function(a){return b._mouseMove(a)},this._mouseUpDelegate=function(a){return b._mouseUp(a)},this.document.on("mousemove."+this.widgetName,this._mouseMoveDelegate).on("mouseup."+this.widgetName,this._mouseUpDelegate),a.preventDefault(),n=!0,!0)):!0}},_mouseMove:function(a){if(this._mouseMoved){if(c.ui.ie&&(!document.documentMode||9>document.documentMode)&&!a.button)return this._mouseUp(a);
if(!a.which)if(a.originalEvent.altKey||a.originalEvent.ctrlKey||a.originalEvent.metaKey||a.originalEvent.shiftKey)this.ignoreMissingWhich=!0;else if(!this.ignoreMissingWhich)return this._mouseUp(a)}return(a.which||a.button)&&(this._mouseMoved=!0),this._mouseStarted?(this._mouseDrag(a),a.preventDefault()):(this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&(this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,a),this._mouseStarted?this._mouseDrag(a):this._mouseUp(a)),!this._mouseStarted)},
_mouseUp:function(a){this.document.off("mousemove."+this.widgetName,this._mouseMoveDelegate).off("mouseup."+this.widgetName,this._mouseUpDelegate);this._mouseStarted&&(this._mouseStarted=!1,a.target===this._mouseDownEvent.target&&c.data(a.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(a));this._mouseDelayTimer&&(clearTimeout(this._mouseDelayTimer),delete this._mouseDelayTimer);n=this.ignoreMissingWhich=!1;a.preventDefault()},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-
a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}});c.widget("ui.slider",c.ui.mouse,{version:"1.12.1",widgetEventPrefix:"slide",options:{animate:!1,classes:{"ui-slider":"ui-corner-all","ui-slider-handle":"ui-corner-all","ui-slider-range":"ui-corner-all ui-widget-header"},distance:0,max:100,min:0,orientation:"horizontal",
range:!1,step:1,value:0,values:null,change:null,slide:null,start:null,stop:null},numPages:5,_create:function(){this._mouseSliding=this._keySliding=!1;this._animateOff=!0;this._handleIndex=null;this._detectOrientation();this._mouseInit();this._calculateNewMax();this._addClass("ui-slider ui-slider-"+this.orientation,"ui-widget ui-widget-content");this._refresh();this._animateOff=!1},_refresh:function(){this._createRange();this._createHandles();this._setupEvents();this._refreshValue()},_createHandles:function(){var a,
b;a=this.options;var e=this.element.find(".ui-slider-handle"),d=[];b=a.values&&a.values.length||1;e.length>b&&(e.slice(b).remove(),e=e.slice(0,b));for(a=e.length;b>a;a++)d.push("<span tabindex='0'></span>");this.handles=e.add(c(d.join("")).appendTo(this.element));this._addClass(this.handles,"ui-slider-handle","ui-state-default");this.handle=this.handles.eq(0);this.handles.each(function(a){c(this).data("ui-slider-handle-index",a).attr("tabIndex",0)})},_createRange:function(){var a=this.options;a.range?
(!0===a.range&&(a.values?a.values.length&&2!==a.values.length?a.values=[a.values[0],a.values[0]]:c.isArray(a.values)&&(a.values=a.values.slice(0)):a.values=[this._valueMin(),this._valueMin()]),this.range&&this.range.length?(this._removeClass(this.range,"ui-slider-range-min ui-slider-range-max"),this.range.css({left:"",bottom:""})):(this.range=c("<div>").appendTo(this.element),this._addClass(this.range,"ui-slider-range")),("min"===a.range||"max"===a.range)&&this._addClass(this.range,"ui-slider-range-"+
a.range)):(this.range&&this.range.remove(),this.range=null)},_setupEvents:function(){this._off(this.handles);this._on(this.handles,this._handleEvents);this._hoverable(this.handles);this._focusable(this.handles)},_destroy:function(){this.handles.remove();this.range&&this.range.remove();this._mouseDestroy()},_mouseCapture:function(a){var b,e,d,f,g,k,m,h,l=this,n=this.options;return n.disabled?!1:(this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()},this.elementOffset=
this.element.offset(),b={x:a.pageX,y:a.pageY},e=this._normValueFromMouse(b),d=this._valueMax()-this._valueMin()+1,this.handles.each(function(a){var b=Math.abs(e-l.values(a));(d>b||d===b&&(a===l._lastChangedValue||l.values(a)===n.min))&&(d=b,f=c(this),g=a)}),k=this._start(a,g),!1===k?!1:(this._mouseSliding=!0,this._handleIndex=g,this._addClass(f,null,"ui-state-active"),f.trigger("focus"),m=f.offset(),h=!c(a.target).parents().addBack().is(".ui-slider-handle"),this._clickOffset=h?{left:0,top:0}:{left:a.pageX-
m.left-f.width()/2,top:a.pageY-m.top-f.height()/2-(parseInt(f.css("borderTopWidth"),10)||0)-(parseInt(f.css("borderBottomWidth"),10)||0)+(parseInt(f.css("marginTop"),10)||0)},this.handles.hasClass("ui-state-hover")||this._slide(a,g,e),this._animateOff=!0,!0))},_mouseStart:function(){return!0},_mouseDrag:function(a){var b=this._normValueFromMouse({x:a.pageX,y:a.pageY});return this._slide(a,this._handleIndex,b),!1},_mouseStop:function(a){return this._removeClass(this.handles,null,"ui-state-active"),
this._mouseSliding=!1,this._stop(a,this._handleIndex),this._change(a,this._handleIndex),this._handleIndex=null,this._clickOffset=null,this._animateOff=!1,!1},_detectOrientation:function(){this.orientation="vertical"===this.options.orientation?"vertical":"horizontal"},_normValueFromMouse:function(a){var b,c,d,f,g;return"horizontal"===this.orientation?(b=this.elementSize.width,c=a.x-this.elementOffset.left-(this._clickOffset?this._clickOffset.left:0)):(b=this.elementSize.height,c=a.y-this.elementOffset.top-
(this._clickOffset?this._clickOffset.top:0)),d=c/b,1<d&&(d=1),0>d&&(d=0),"vertical"===this.orientation&&(d=1-d),f=this._valueMax()-this._valueMin(),g=this._valueMin()+d*f,this._trimAlignValue(g)},_uiHash:function(a,b,c){var e={handle:this.handles[a],handleIndex:a,value:void 0!==b?b:this.value()};return this._hasMultipleValues()&&(e.value=void 0!==b?b:this.values(a),e.values=c||this.values()),e},_hasMultipleValues:function(){return this.options.values&&this.options.values.length},_start:function(a,
b){return this._trigger("start",a,this._uiHash(b))},_slide:function(a,b,c){var e,f,g=this.value(),k=this.values();this._hasMultipleValues()&&(f=this.values(b?0:1),g=this.values(b),2===this.options.values.length&&!0===this.options.range&&(c=0===b?Math.min(f,c):Math.max(f,c)),k[b]=c);c!==g&&(e=this._trigger("slide",a,this._uiHash(b,c,k)),!1!==e&&(this._hasMultipleValues()?this.values(b,c):this.value(c)))},_stop:function(a,b){this._trigger("stop",a,this._uiHash(b))},_change:function(a,b){this._keySliding||
this._mouseSliding||(this._lastChangedValue=b,this._trigger("change",a,this._uiHash(b)))},value:function(a){return arguments.length?(this.options.value=this._trimAlignValue(a),this._refreshValue(),this._change(null,0),void 0):this._value()},values:function(a,b){var e,d,f;if(1<arguments.length)return this.options.values[a]=this._trimAlignValue(b),this._refreshValue(),this._change(null,a),void 0;if(!arguments.length)return this._values();if(!c.isArray(arguments[0]))return this._hasMultipleValues()?
this._values(a):this.value();e=this.options.values;d=arguments[0];for(f=0;e.length>f;f+=1)e[f]=this._trimAlignValue(d[f]),this._change(null,f);this._refreshValue()},_setOption:function(a,b){var e;e=0;switch("range"===a&&!0===this.options.range&&("min"===b?(this.options.value=this._values(0),this.options.values=null):"max"===b&&(this.options.value=this._values(this.options.values.length-1),this.options.values=null)),c.isArray(this.options.values)&&(e=this.options.values.length),this._super(a,b),a){case "orientation":this._detectOrientation();
this._removeClass("ui-slider-horizontal ui-slider-vertical")._addClass("ui-slider-"+this.orientation);this._refreshValue();this.options.range&&this._refreshRange(b);this.handles.css("horizontal"===b?"bottom":"left","");break;case "value":this._animateOff=!0;this._refreshValue();this._change(null,0);this._animateOff=!1;break;case "values":this._animateOff=!0;this._refreshValue();for(--e;0<=e;e--)this._change(null,e);this._animateOff=!1;break;case "step":case "min":case "max":this._animateOff=!0;this._calculateNewMax();
this._refreshValue();this._animateOff=!1;break;case "range":this._animateOff=!0,this._refresh(),this._animateOff=!1}},_setOptionDisabled:function(a){this._super(a);this._toggleClass(null,"ui-state-disabled",!!a)},_value:function(){return this._trimAlignValue(this.options.value)},_values:function(a){var b,c;if(arguments.length)return b=this.options.values[a],this._trimAlignValue(b);if(this._hasMultipleValues()){b=this.options.values.slice();for(c=0;b.length>c;c+=1)b[c]=this._trimAlignValue(b[c]);return b}return[]},
_trimAlignValue:function(a){if(this._valueMin()>=a)return this._valueMin();if(a>=this._valueMax())return this._valueMax();var b=0<this.options.step?this.options.step:1,c=(a-this._valueMin())%b;a-=c;return 2*Math.abs(c)>=b&&(a+=0<c?b:-b),parseFloat(a.toFixed(5))},_calculateNewMax:function(){var a=this.options.max,b=this._valueMin(),c=this.options.step,a=Math.round((a-b)/c)*c+b;a>this.options.max&&(a-=c);this.max=parseFloat(a.toFixed(this._precision()))},_precision:function(){var a=this._precisionOf(this.options.step);
return null!==this.options.min&&(a=Math.max(a,this._precisionOf(this.options.min))),a},_precisionOf:function(a){a=""+a;var b=a.indexOf(".");return-1===b?0:a.length-b-1},_valueMin:function(){return this.options.min},_valueMax:function(){return this.max},_refreshRange:function(a){"vertical"===a&&this.range.css({width:"",left:""});"horizontal"===a&&this.range.css({height:"",bottom:""})},_refreshValue:function(){var a,b,e,d,f,g=this.options.range,k=this.options,m=this,h=this._animateOff?!1:k.animate,
l={};this._hasMultipleValues()?this.handles.each(function(d){b=100*((m.values(d)-m._valueMin())/(m._valueMax()-m._valueMin()));l["horizontal"===m.orientation?"left":"bottom"]=b+"%";c(this).stop(1,1)[h?"animate":"css"](l,k.animate);!0===m.options.range&&("horizontal"===m.orientation?(0===d&&m.range.stop(1,1)[h?"animate":"css"]({left:b+"%"},k.animate),1===d&&m.range[h?"animate":"css"]({width:b-a+"%"},{queue:!1,duration:k.animate})):(0===d&&m.range.stop(1,1)[h?"animate":"css"]({bottom:b+"%"},k.animate),
1===d&&m.range[h?"animate":"css"]({height:b-a+"%"},{queue:!1,duration:k.animate})));a=b}):(e=this.value(),d=this._valueMin(),f=this._valueMax(),b=f!==d?(e-d)/(f-d)*100:0,l["horizontal"===this.orientation?"left":"bottom"]=b+"%",this.handle.stop(1,1)[h?"animate":"css"](l,k.animate),"min"===g&&"horizontal"===this.orientation&&this.range.stop(1,1)[h?"animate":"css"]({width:b+"%"},k.animate),"max"===g&&"horizontal"===this.orientation&&this.range.stop(1,1)[h?"animate":"css"]({width:100-b+"%"},k.animate),
"min"===g&&"vertical"===this.orientation&&this.range.stop(1,1)[h?"animate":"css"]({height:b+"%"},k.animate),"max"===g&&"vertical"===this.orientation&&this.range.stop(1,1)[h?"animate":"css"]({height:100-b+"%"},k.animate))},_handleEvents:{keydown:function(a){var b,e,d,f=c(a.target).data("ui-slider-handle-index");switch(a.keyCode){case c.ui.keyCode.HOME:case c.ui.keyCode.END:case c.ui.keyCode.PAGE_UP:case c.ui.keyCode.PAGE_DOWN:case c.ui.keyCode.UP:case c.ui.keyCode.RIGHT:case c.ui.keyCode.DOWN:case c.ui.keyCode.LEFT:if(a.preventDefault(),
!this._keySliding&&(this._keySliding=!0,this._addClass(c(a.target),null,"ui-state-active"),b=this._start(a,f),!1===b))return}switch(d=this.options.step,b=e=this._hasMultipleValues()?this.values(f):this.value(),a.keyCode){case c.ui.keyCode.HOME:e=this._valueMin();break;case c.ui.keyCode.END:e=this._valueMax();break;case c.ui.keyCode.PAGE_UP:e=this._trimAlignValue(b+(this._valueMax()-this._valueMin())/this.numPages);break;case c.ui.keyCode.PAGE_DOWN:e=this._trimAlignValue(b-(this._valueMax()-this._valueMin())/
this.numPages);break;case c.ui.keyCode.UP:case c.ui.keyCode.RIGHT:if(b===this._valueMax())return;e=this._trimAlignValue(b+d);break;case c.ui.keyCode.DOWN:case c.ui.keyCode.LEFT:if(b===this._valueMin())return;e=this._trimAlignValue(b-d)}this._slide(a,f,e)},keyup:function(a){var b=c(a.target).data("ui-slider-handle-index");this._keySliding&&(this._keySliding=!1,this._stop(a,b),this._change(a,b),this._removeClass(c(a.target),null,"ui-state-active"))}}})});
(function(c){function l(a,c){if(!(1<a.originalEvent.touches.length)){a.preventDefault();var b=a.originalEvent.changedTouches[0],e=document.createEvent("MouseEvents");e.initMouseEvent(c,!0,!0,window,1,b.screenX,b.screenY,b.clientX,b.clientY,!1,!1,!1,!1,0,null);a.target.dispatchEvent(e)}}c.support.touch="ontouchend"in document;if(c.support.touch){var h=c.ui.mouse.prototype,n=h._mouseInit,a;h._touchStart=function(b){!a&&this._mouseCapture(b.originalEvent.changedTouches[0])&&(a=!0,this._touchMoved=!1,
l(b,"mouseover"),l(b,"mousemove"),l(b,"mousedown"))};h._touchMove=function(b){a&&(this._touchMoved=!0,l(b,"mousemove"))};h._touchEnd=function(b){a&&(l(b,"mouseup"),l(b,"mouseout"),this._touchMoved||l(b,"click"),a=!1)};h._mouseInit=function(){this.element.bind("touchstart",c.proxy(this,"_touchStart")).bind("touchmove",c.proxy(this,"_touchMove")).bind("touchend",c.proxy(this,"_touchEnd"));n.call(this)}}})(jQuery);