/*
 jQuery UI - v1.12.1 - 2016-10-03 * http://jqueryui.com * Includes: widget.js, keycode.js, widgets/mouse.js, widgets/slider.js * Copyright jQuery Foundation and other contributors; Licensed MIT */
(function(c){"function"==typeof define&&define.amd?define(["jquery"],c):c(jQuery)})(function(c){c.ui=c.ui||{};c.ui.version="1.12.1";var r=0,p=Array.prototype.slice;c.cleanData=function(a){return function(b){var d,e,f;for(f=0;null!=(e=b[f]);f++)try{(d=c._data(e,"events"))&&d.remove&&c(e).triggerHandler("remove")}catch(g){}a(b)}}(c.cleanData);c.widget=function(a,b,d){var e,f,g,h={},k=a.split(".")[0];a=a.split(".")[1];var l=k+"-"+a;return d||(d=b,b=c.Widget),c.isArray(d)&&(d=c.extend.apply(null,[{}].concat(d))),
c.expr[":"][l.toLowerCase()]=function(a){return!!c.data(a,l)},c[k]=c[k]||{},e=c[k][a],f=c[k][a]=function(a,b){return this._createWidget?(arguments.length&&this._createWidget(a,b),void 0):new f(a,b)},c.extend(f,e,{version:d.version,_proto:c.extend({},d),_childConstructors:[]}),g=new b,g.options=c.widget.extend({},g.options),c.each(d,function(a,d){return c.isFunction(d)?(h[a]=function(){function c(){return b.prototype[a].apply(this,arguments)}function e(d){return b.prototype[a].apply(this,d)}return function(){var a,
b=this._super,f=this._superApply;return this._super=c,this._superApply=e,a=d.apply(this,arguments),this._super=b,this._superApply=f,a}}(),void 0):(h[a]=d,void 0)}),f.prototype=c.widget.extend(g,{widgetEventPrefix:e?g.widgetEventPrefix||a:a},h,{constructor:f,namespace:k,widgetName:a,widgetFullName:l}),e?(c.each(e._childConstructors,function(a,b){var d=b.prototype;c.widget(d.namespace+"."+d.widgetName,f,b._proto)}),delete e._childConstructors):b._childConstructors.push(f),c.widget.bridge(a,f),f};c.widget.extend=
function(a){for(var b,d,e=p.call(arguments,1),f=0,g=e.length;g>f;f++)for(b in e[f])d=e[f][b],e[f].hasOwnProperty(b)&&void 0!==d&&(a[b]=c.isPlainObject(d)?c.isPlainObject(a[b])?c.widget.extend({},a[b],d):c.widget.extend({},d):d);return a};c.widget.bridge=function(a,b){var d=b.prototype.widgetFullName||a;c.fn[a]=function(e){var f="string"==typeof e,g=p.call(arguments,1),h=this;return f?this.length||"instance"!==e?this.each(function(){var b,f=c.data(this,d);return"instance"===e?(h=f,!1):f?c.isFunction(f[e])&&
"_"!==e.charAt(0)?(b=f[e].apply(f,g),b!==f&&void 0!==b?(h=b&&b.jquery?h.pushStack(b.get()):b,!1):void 0):c.error("no such method '"+e+"' for "+a+" widget instance"):c.error("cannot call methods on "+a+" prior to initialization; attempted to call method '"+e+"'")}):h=void 0:(g.length&&(e=c.widget.extend.apply(null,[e].concat(g))),this.each(function(){var a=c.data(this,d);a?(a.option(e||{}),a._init&&a._init()):c.data(this,d,new b(e,this))})),h}};c.Widget=function(){};c.Widget._childConstructors=[];
c.Widget.prototype={widgetName:"widget",widgetEventPrefix:"",defaultElement:"<div>",options:{classes:{},disabled:!1,create:null},_createWidget:function(a,b){b=c(b||this.defaultElement||this)[0];this.element=c(b);this.uuid=r++;this.eventNamespace="."+this.widgetName+this.uuid;this.bindings=c();this.hoverable=c();this.focusable=c();this.classesElementLookup={};b!==this&&(c.data(b,this.widgetFullName,this),this._on(!0,this.element,{remove:function(a){a.target===b&&this.destroy()}}),this.document=c(b.style?
b.ownerDocument:b.document||b),this.window=c(this.document[0].defaultView||this.document[0].parentWindow));this.options=c.widget.extend({},this.options,this._getCreateOptions(),a);this._create();this.options.disabled&&this._setOptionDisabled(this.options.disabled);this._trigger("create",null,this._getCreateEventData());this._init()},_getCreateOptions:function(){return{}},_getCreateEventData:c.noop,_create:c.noop,_init:c.noop,destroy:function(){var a=this;this._destroy();c.each(this.classesElementLookup,
function(b,d){a._removeClass(d,b)});this.element.off(this.eventNamespace).removeData(this.widgetFullName);this.widget().off(this.eventNamespace).removeAttr("aria-disabled");this.bindings.off(this.eventNamespace)},_destroy:c.noop,widget:function(){return this.element},option:function(a,b){var d,e,f=a;if(0===arguments.length)return c.widget.extend({},this.options);if("string"==typeof a)if(f={},d=a.split("."),a=d.shift(),d.length){var g=f[a]=c.widget.extend({},this.options[a]);for(e=0;d.length-1>e;e++)g[d[e]]=
g[d[e]]||{},g=g[d[e]];if(a=d.pop(),1===arguments.length)return void 0===g[a]?null:g[a];g[a]=b}else{if(1===arguments.length)return void 0===this.options[a]?null:this.options[a];f[a]=b}return this._setOptions(f),this},_setOptions:function(a){for(var b in a)this._setOption(b,a[b]);return this},_setOption:function(a,b){return"classes"===a&&this._setOptionClasses(b),this.options[a]=b,"disabled"===a&&this._setOptionDisabled(b),this},_setOptionClasses:function(a){var b,d;for(b in a){var e=this.classesElementLookup[b];
a[b]!==this.options.classes[b]&&e&&e.length&&(d=c(e.get()),this._removeClass(e,b),d.addClass(this._classes({element:d,keys:b,classes:a,add:!0})))}},_setOptionDisabled:function(a){this._toggleClass(this.widget(),this.widgetFullName+"-disabled",null,!!a);a&&(this._removeClass(this.hoverable,null,"ui-state-hover"),this._removeClass(this.focusable,null,"ui-state-focus"))},enable:function(){return this._setOptions({disabled:!1})},disable:function(){return this._setOptions({disabled:!0})},_classes:function(a){function b(b,
g){var f;for(f=0;b.length>f;f++){var k=e.classesElementLookup[b[f]]||c();k=a.add?c(c.unique(k.get().concat(a.element.get()))):c(k.not(a.element).get());e.classesElementLookup[b[f]]=k;d.push(b[f]);g&&a.classes[b[f]]&&d.push(a.classes[b[f]])}}var d=[],e=this;return a=c.extend({element:this.element,classes:this.options.classes||{}},a),this._on(a.element,{remove:"_untrackClassesElement"}),a.keys&&b(a.keys.match(/\S+/g)||[],!0),a.extra&&b(a.extra.match(/\S+/g)||[]),d.join(" ")},_untrackClassesElement:function(a){var b=
this;c.each(b.classesElementLookup,function(d,e){-1!==c.inArray(a.target,e)&&(b.classesElementLookup[d]=c(e.not(a.target).get()))})},_removeClass:function(a,b,d){return this._toggleClass(a,b,d,!1)},_addClass:function(a,b,d){return this._toggleClass(a,b,d,!0)},_toggleClass:function(a,b,d,c){c="boolean"==typeof c?c:d;var e="string"==typeof a||null===a;a={extra:e?b:d,keys:e?a:b,element:e?this.element:a,add:c};return a.element.toggleClass(this._classes(a),c),this},_on:function(a,b,d){var e,f=this;"boolean"!=
typeof a&&(d=b,b=a,a=!1);d?(b=e=c(b),this.bindings=this.bindings.add(b)):(d=b,b=this.element,e=this.widget());c.each(d,function(d,h){function g(){return a||!0!==f.options.disabled&&!c(this).hasClass("ui-state-disabled")?("string"==typeof h?f[h]:h).apply(f,arguments):void 0}"string"!=typeof h&&(g.guid=h.guid=h.guid||g.guid||c.guid++);var l=d.match(/^([\w:-]*)\s*(.*)$/),m=l[1]+f.eventNamespace;(l=l[2])?e.on(m,l,g):b.on(m,g)})},_off:function(a,b){b=(b||"").split(" ").join(this.eventNamespace+" ")+this.eventNamespace;
a.off(b).off(b);this.bindings=c(this.bindings.not(a).get());this.focusable=c(this.focusable.not(a).get());this.hoverable=c(this.hoverable.not(a).get())},_delay:function(a,b){var d=this;return setTimeout(function(){return("string"==typeof a?d[a]:a).apply(d,arguments)},b||0)},_hoverable:function(a){this.hoverable=this.hoverable.add(a);this._on(a,{mouseenter:function(a){this._addClass(c(a.currentTarget),null,"ui-state-hover")},mouseleave:function(a){this._removeClass(c(a.currentTarget),null,"ui-state-hover")}})},
_focusable:function(a){this.focusable=this.focusable.add(a);this._on(a,{focusin:function(a){this._addClass(c(a.currentTarget),null,"ui-state-focus")},focusout:function(a){this._removeClass(c(a.currentTarget),null,"ui-state-focus")}})},_trigger:function(a,b,d){var e,f=this.options[a];if(d=d||{},b=c.Event(b),b.type=(a===this.widgetEventPrefix?a:this.widgetEventPrefix+a).toLowerCase(),b.target=this.element[0],a=b.originalEvent)for(e in a)e in b||(b[e]=a[e]);return this.element.trigger(b,d),!(c.isFunction(f)&&
!1===f.apply(this.element[0],[b].concat(d))||b.isDefaultPrevented())}};c.each({show:"fadeIn",hide:"fadeOut"},function(a,b){c.Widget.prototype["_"+a]=function(d,e,f){"string"==typeof e&&(e={effect:e});var g=e?!0===e||"number"==typeof e?b:e.effect||b:a;e=e||{};"number"==typeof e&&(e={duration:e});var h=!c.isEmptyObject(e);e.complete=f;e.delay&&d.delay(e.delay);h&&c.effects&&c.effects.effect[g]?d[a](e):g!==a&&d[g]?d[g](e.duration,e.easing,f):d.queue(function(b){c(this)[a]();f&&f.call(d[0]);b()})}});
c.widget;c.ui.keyCode={BACKSPACE:8,COMMA:188,DELETE:46,DOWN:40,END:35,ENTER:13,ESCAPE:27,HOME:36,LEFT:37,PAGE_DOWN:34,PAGE_UP:33,PERIOD:190,RIGHT:39,SPACE:32,TAB:9,UP:38};c.ui.ie=!!/msie [\w.]+/.exec(navigator.userAgent.toLowerCase());var n=!1;c(document).on("mouseup",function(){n=!1});c.widget("ui.mouse",{version:"1.12.1",options:{cancel:"input, textarea, button, select, option",distance:1,delay:0},_mouseInit:function(){var a=this;this.element.on("mousedown."+this.widgetName,function(b){return a._mouseDown(b)}).on("click."+
this.widgetName,function(b){return!0===c.data(b.target,a.widgetName+".preventClickEvent")?(c.removeData(b.target,a.widgetName+".preventClickEvent"),b.stopImmediatePropagation(),!1):void 0});this.started=!1},_mouseDestroy:function(){this.element.off("."+this.widgetName);this._mouseMoveDelegate&&this.document.off("mousemove."+this.widgetName,this._mouseMoveDelegate).off("mouseup."+this.widgetName,this._mouseUpDelegate)},_mouseDown:function(a){if(!n){this._mouseMoved=!1;this._mouseStarted&&this._mouseUp(a);
this._mouseDownEvent=a;var b=this,d=1===a.which,e="string"==typeof this.options.cancel&&a.target.nodeName?c(a.target).closest(this.options.cancel).length:!1;return d&&!e&&this._mouseCapture(a)?(this.mouseDelayMet=!this.options.delay,this.mouseDelayMet||(this._mouseDelayTimer=setTimeout(function(){b.mouseDelayMet=!0},this.options.delay)),this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&(this._mouseStarted=!1!==this._mouseStart(a),!this._mouseStarted)?(a.preventDefault(),!0):(!0===c.data(a.target,
this.widgetName+".preventClickEvent")&&c.removeData(a.target,this.widgetName+".preventClickEvent"),this._mouseMoveDelegate=function(a){return b._mouseMove(a)},this._mouseUpDelegate=function(a){return b._mouseUp(a)},this.document.on("mousemove."+this.widgetName,this._mouseMoveDelegate).on("mouseup."+this.widgetName,this._mouseUpDelegate),a.preventDefault(),n=!0,!0)):!0}},_mouseMove:function(a){if(this._mouseMoved){if(c.ui.ie&&(!document.documentMode||9>document.documentMode)&&!a.button)return this._mouseUp(a);
if(!a.which)if(a.originalEvent.altKey||a.originalEvent.ctrlKey||a.originalEvent.metaKey||a.originalEvent.shiftKey)this.ignoreMissingWhich=!0;else if(!this.ignoreMissingWhich)return this._mouseUp(a)}return(a.which||a.button)&&(this._mouseMoved=!0),this._mouseStarted?(this._mouseDrag(a),a.preventDefault()):(this._mouseDistanceMet(a)&&this._mouseDelayMet(a)&&(this._mouseStarted=!1!==this._mouseStart(this._mouseDownEvent,a),this._mouseStarted?this._mouseDrag(a):this._mouseUp(a)),!this._mouseStarted)},
_mouseUp:function(a){this.document.off("mousemove."+this.widgetName,this._mouseMoveDelegate).off("mouseup."+this.widgetName,this._mouseUpDelegate);this._mouseStarted&&(this._mouseStarted=!1,a.target===this._mouseDownEvent.target&&c.data(a.target,this.widgetName+".preventClickEvent",!0),this._mouseStop(a));this._mouseDelayTimer&&(clearTimeout(this._mouseDelayTimer),delete this._mouseDelayTimer);n=this.ignoreMissingWhich=!1;a.preventDefault()},_mouseDistanceMet:function(a){return Math.max(Math.abs(this._mouseDownEvent.pageX-
a.pageX),Math.abs(this._mouseDownEvent.pageY-a.pageY))>=this.options.distance},_mouseDelayMet:function(){return this.mouseDelayMet},_mouseStart:function(){},_mouseDrag:function(){},_mouseStop:function(){},_mouseCapture:function(){return!0}});c.widget("ui.slider",c.ui.mouse,{version:"1.12.1",widgetEventPrefix:"slide",options:{animate:!1,classes:{"ui-slider":"ui-corner-all","ui-slider-handle":"ui-corner-all","ui-slider-range":"ui-corner-all ui-widget-header"},distance:0,max:100,min:0,orientation:"horizontal",
range:!1,step:1,value:0,values:null,change:null,slide:null,start:null,stop:null},numPages:5,_create:function(){this._mouseSliding=this._keySliding=!1;this._animateOff=!0;this._handleIndex=null;this._detectOrientation();this._mouseInit();this._calculateNewMax();this._addClass("ui-slider ui-slider-"+this.orientation,"ui-widget ui-widget-content");this._refresh();this._animateOff=!1},_refresh:function(){this._createRange();this._createHandles();this._setupEvents();this._refreshValue()},_createHandles:function(){var a=
this.options;var b=this.element.find(".ui-slider-handle"),d=[];var e=a.values&&a.values.length||1;b.length>e&&(b.slice(e).remove(),b=b.slice(0,e));for(a=b.length;e>a;a++)d.push("<span tabindex='0'></span>");this.handles=b.add(c(d.join("")).appendTo(this.element));this._addClass(this.handles,"ui-slider-handle","ui-state-default");this.handle=this.handles.eq(0);this.handles.each(function(a){c(this).data("ui-slider-handle-index",a).attr("tabIndex",0)})},_createRange:function(){var a=this.options;a.range?
(!0===a.range&&(a.values?a.values.length&&2!==a.values.length?a.values=[a.values[0],a.values[0]]:c.isArray(a.values)&&(a.values=a.values.slice(0)):a.values=[this._valueMin(),this._valueMin()]),this.range&&this.range.length?(this._removeClass(this.range,"ui-slider-range-min ui-slider-range-max"),this.range.css({left:"",bottom:""})):(this.range=c("<div>").appendTo(this.element),this._addClass(this.range,"ui-slider-range")),("min"===a.range||"max"===a.range)&&this._addClass(this.range,"ui-slider-range-"+
a.range)):(this.range&&this.range.remove(),this.range=null)},_setupEvents:function(){this._off(this.handles);this._on(this.handles,this._handleEvents);this._hoverable(this.handles);this._focusable(this.handles)},_destroy:function(){this.handles.remove();this.range&&this.range.remove();this._mouseDestroy()},_mouseCapture:function(a){var b,d,e,f,g,h,k,l,m=this,q=this.options;return q.disabled?!1:(this.elementSize={width:this.element.outerWidth(),height:this.element.outerHeight()},this.elementOffset=
this.element.offset(),b={x:a.pageX,y:a.pageY},d=this._normValueFromMouse(b),e=this._valueMax()-this._valueMin()+1,this.handles.each(function(a){var b=Math.abs(d-m.values(a));(e>b||e===b&&(a===m._lastChangedValue||m.values(a)===q.min))&&(e=b,f=c(this),g=a)}),h=this._start(a,g),!1===h?!1:(this._mouseSliding=!0,this._handleIndex=g,this._addClass(f,null,"ui-state-active"),f.trigger("focus"),k=f.offset(),l=!c(a.target).parents().addBack().is(".ui-slider-handle"),this._clickOffset=l?{left:0,top:0}:{left:a.pageX-
k.left-f.width()/2,top:a.pageY-k.top-f.height()/2-(parseInt(f.css("borderTopWidth"),10)||0)-(parseInt(f.css("borderBottomWidth"),10)||0)+(parseInt(f.css("marginTop"),10)||0)},this.handles.hasClass("ui-state-hover")||this._slide(a,g,d),this._animateOff=!0,!0))},_mouseStart:function(){return!0},_mouseDrag:function(a){var b=this._normValueFromMouse({x:a.pageX,y:a.pageY});return this._slide(a,this._handleIndex,b),!1},_mouseStop:function(a){return this._removeClass(this.handles,null,"ui-state-active"),
this._mouseSliding=!1,this._stop(a,this._handleIndex),this._change(a,this._handleIndex),this._handleIndex=null,this._clickOffset=null,this._animateOff=!1,!1},_detectOrientation:function(){this.orientation="vertical"===this.options.orientation?"vertical":"horizontal"},_normValueFromMouse:function(a){var b,d,c,f,g;return"horizontal"===this.orientation?(b=this.elementSize.width,d=a.x-this.elementOffset.left-(this._clickOffset?this._clickOffset.left:0)):(b=this.elementSize.height,d=a.y-this.elementOffset.top-
(this._clickOffset?this._clickOffset.top:0)),c=d/b,1<c&&(c=1),0>c&&(c=0),"vertical"===this.orientation&&(c=1-c),f=this._valueMax()-this._valueMin(),g=this._valueMin()+c*f,this._trimAlignValue(g)},_uiHash:function(a,b,c){var d={handle:this.handles[a],handleIndex:a,value:void 0!==b?b:this.value()};return this._hasMultipleValues()&&(d.value=void 0!==b?b:this.values(a),d.values=c||this.values()),d},_hasMultipleValues:function(){return this.options.values&&this.options.values.length},_start:function(a,
b){return this._trigger("start",a,this._uiHash(b))},_slide:function(a,b,c){var d,f,g=this.value(),h=this.values();this._hasMultipleValues()&&(f=this.values(b?0:1),g=this.values(b),2===this.options.values.length&&!0===this.options.range&&(c=0===b?Math.min(f,c):Math.max(f,c)),h[b]=c);c!==g&&(d=this._trigger("slide",a,this._uiHash(b,c,h)),!1!==d&&(this._hasMultipleValues()?this.values(b,c):this.value(c)))},_stop:function(a,b){this._trigger("stop",a,this._uiHash(b))},_change:function(a,b){this._keySliding||
this._mouseSliding||(this._lastChangedValue=b,this._trigger("change",a,this._uiHash(b)))},value:function(a){return arguments.length?(this.options.value=this._trimAlignValue(a),this._refreshValue(),this._change(null,0),void 0):this._value()},values:function(a,b){var d;if(1<arguments.length)return this.options.values[a]=this._trimAlignValue(b),this._refreshValue(),this._change(null,a),void 0;if(!arguments.length)return this._values();if(!c.isArray(arguments[0]))return this._hasMultipleValues()?this._values(a):
this.value();var e=this.options.values;var f=arguments[0];for(d=0;e.length>d;d+=1)e[d]=this._trimAlignValue(f[d]),this._change(null,d);this._refreshValue()},_setOption:function(a,b){var d=0;switch("range"===a&&!0===this.options.range&&("min"===b?(this.options.value=this._values(0),this.options.values=null):"max"===b&&(this.options.value=this._values(this.options.values.length-1),this.options.values=null)),c.isArray(this.options.values)&&(d=this.options.values.length),this._super(a,b),a){case "orientation":this._detectOrientation();
this._removeClass("ui-slider-horizontal ui-slider-vertical")._addClass("ui-slider-"+this.orientation);this._refreshValue();this.options.range&&this._refreshRange(b);this.handles.css("horizontal"===b?"bottom":"left","");break;case "value":this._animateOff=!0;this._refreshValue();this._change(null,0);this._animateOff=!1;break;case "values":this._animateOff=!0;this._refreshValue();for(--d;0<=d;d--)this._change(null,d);this._animateOff=!1;break;case "step":case "min":case "max":this._animateOff=!0;this._calculateNewMax();
this._refreshValue();this._animateOff=!1;break;case "range":this._animateOff=!0,this._refresh(),this._animateOff=!1}},_setOptionDisabled:function(a){this._super(a);this._toggleClass(null,"ui-state-disabled",!!a)},_value:function(){return this._trimAlignValue(this.options.value)},_values:function(a){var b,c;if(arguments.length)return b=this.options.values[a],this._trimAlignValue(b);if(this._hasMultipleValues()){b=this.options.values.slice();for(c=0;b.length>c;c+=1)b[c]=this._trimAlignValue(b[c]);return b}return[]},
_trimAlignValue:function(a){if(this._valueMin()>=a)return this._valueMin();if(a>=this._valueMax())return this._valueMax();var b=0<this.options.step?this.options.step:1,c=(a-this._valueMin())%b;a-=c;return 2*Math.abs(c)>=b&&(a+=0<c?b:-b),parseFloat(a.toFixed(5))},_calculateNewMax:function(){var a=this.options.max,b=this._valueMin(),c=this.options.step;a=Math.round((a-b)/c)*c+b;a>this.options.max&&(a-=c);this.max=parseFloat(a.toFixed(this._precision()))},_precision:function(){var a=this._precisionOf(this.options.step);
return null!==this.options.min&&(a=Math.max(a,this._precisionOf(this.options.min))),a},_precisionOf:function(a){a=""+a;var b=a.indexOf(".");return-1===b?0:a.length-b-1},_valueMin:function(){return this.options.min},_valueMax:function(){return this.max},_refreshRange:function(a){"vertical"===a&&this.range.css({width:"",left:""});"horizontal"===a&&this.range.css({height:"",bottom:""})},_refreshValue:function(){var a,b,d,e,f,g=this.options.range,h=this.options,k=this,l=this._animateOff?!1:h.animate,
m={};this._hasMultipleValues()?this.handles.each(function(d){b=100*((k.values(d)-k._valueMin())/(k._valueMax()-k._valueMin()));m["horizontal"===k.orientation?"left":"bottom"]=b+"%";c(this).stop(1,1)[l?"animate":"css"](m,h.animate);!0===k.options.range&&("horizontal"===k.orientation?(0===d&&k.range.stop(1,1)[l?"animate":"css"]({left:b+"%"},h.animate),1===d&&k.range[l?"animate":"css"]({width:b-a+"%"},{queue:!1,duration:h.animate})):(0===d&&k.range.stop(1,1)[l?"animate":"css"]({bottom:b+"%"},h.animate),
1===d&&k.range[l?"animate":"css"]({height:b-a+"%"},{queue:!1,duration:h.animate})));a=b}):(d=this.value(),e=this._valueMin(),f=this._valueMax(),b=f!==e?(d-e)/(f-e)*100:0,m["horizontal"===this.orientation?"left":"bottom"]=b+"%",this.handle.stop(1,1)[l?"animate":"css"](m,h.animate),"min"===g&&"horizontal"===this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({width:b+"%"},h.animate),"max"===g&&"horizontal"===this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({width:100-b+"%"},h.animate),
"min"===g&&"vertical"===this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({height:b+"%"},h.animate),"max"===g&&"vertical"===this.orientation&&this.range.stop(1,1)[l?"animate":"css"]({height:100-b+"%"},h.animate))},_handleEvents:{keydown:function(a){var b,d,e,f=c(a.target).data("ui-slider-handle-index");switch(a.keyCode){case c.ui.keyCode.HOME:case c.ui.keyCode.END:case c.ui.keyCode.PAGE_UP:case c.ui.keyCode.PAGE_DOWN:case c.ui.keyCode.UP:case c.ui.keyCode.RIGHT:case c.ui.keyCode.DOWN:case c.ui.keyCode.LEFT:if(a.preventDefault(),
!this._keySliding&&(this._keySliding=!0,this._addClass(c(a.target),null,"ui-state-active"),b=this._start(a,f),!1===b))return}switch(e=this.options.step,b=d=this._hasMultipleValues()?this.values(f):this.value(),a.keyCode){case c.ui.keyCode.HOME:d=this._valueMin();break;case c.ui.keyCode.END:d=this._valueMax();break;case c.ui.keyCode.PAGE_UP:d=this._trimAlignValue(b+(this._valueMax()-this._valueMin())/this.numPages);break;case c.ui.keyCode.PAGE_DOWN:d=this._trimAlignValue(b-(this._valueMax()-this._valueMin())/
this.numPages);break;case c.ui.keyCode.UP:case c.ui.keyCode.RIGHT:if(b===this._valueMax())return;d=this._trimAlignValue(b+e);break;case c.ui.keyCode.DOWN:case c.ui.keyCode.LEFT:if(b===this._valueMin())return;d=this._trimAlignValue(b-e)}this._slide(a,f,d)},keyup:function(a){var b=c(a.target).data("ui-slider-handle-index");this._keySliding&&(this._keySliding=!1,this._stop(a,b),this._change(a,b),this._removeClass(c(a.target),null,"ui-state-active"))}}})});